name: Fabrício Ronchi - Blog
markdown: redcarpet
pygments: true
name: Fabrício Ronchi
url: http://fabricioronchi.com
domain: fabricioronchi.com
author :
  name : Fabrício Ronchi
  email : fabricioronchii@gmail.com
  github : https://github.com/realronchi
  twitter : https://twitter.com/realronchi
  linkedin : http://br.linkedin.com/in/realronchi
